In [19]:
import numpy as np

In [20]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print(array.ndim) #维度(有几层方括号)

2


In [15]:
print(array.shape) #形状

(3, 3)


In [16]:
print(array.size) #大小

9


In [18]:
print(array.dtype) #元素类型

int32
