In [16]:
import numpy as np

In [21]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1)
print(arr2)

[1 2 3]
[4 5 6]


In [22]:
arr3 = np.vstack((arr1, arr2))

print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [23]:
arr4 = np.hstack((arr1, arr2))

print(arr4)
print(arr4.shape)

[1 2 3 4 5 6]
(6,)


In [24]:
arrv = np.vstack((arr1, arr2, arr3))
print(arrv)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [25]:
arrh = np.hstack((arr1, arr2, arr4))
print(arrh)

[1 2 3 4 5 6 1 2 3 4 5 6]


In [26]:
arr = np.concatenate((arr1, arr2, arr1))
print(arr)

[1 2 3 4 5 6 1 2 3]


In [28]:
arr = np.concatenate((arr3, arrv), axis = 0)
print(arr)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [29]:
arr = np.concatenate((arr3, arr3), axis = 1)
print(arr)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


注：合并的矩阵的维度要相同，形状要匹配

In [31]:
print(arr1.shape)
print(arr1.T) #一维的array无法转置

(3,)
[1 2 3]


In [33]:
arr1_1 = arr1[np.newaxis,:] #增加维度
print(arr1_1)
print(arr1_1.shape)
print(arr1_1.T)

[[1 2 3]]
(1, 3)
[[1]
 [2]
 [3]]


In [39]:
arr1_2 = arr1[:,np.newaxis]
print(arr1_2)
print(arr1_2.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [43]:
arr1_3 = np.atleast_2d(arr1) #至少二维
print(arr1_3)
print(arr1_3.shape)
print(arr1_3.T)

[[1 2 3]]
(1, 3)
[[1]
 [2]
 [3]]
