In [11]:
import numpy as np

In [13]:
a = np.array([1,2,3],dtype=np.int32)
print(a.dtype)

int32


In [14]:
b = np.array([1,2,3],dtype=np.float64)
print(b.dtype)

float64


In [15]:
c = np.array([1,2,3]) #一维数组
print(c)

[1 2 3]


In [17]:
d = np.array([[1,2],[3,4],[5,6],[7,8]]) #二维矩阵
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
zero = np.zeros((2,3)) #生成2行3列全为0的矩阵
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
one = np.ones((3,4)) #生成3行4列全为1的矩阵
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
empty = np.empty((3,2)) #生成3行2列全都无穷小（不为0）的矩阵
print(empty)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [24]:
e = np.arange(10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
f = np.arange(4, 12)
print(f)

[ 4  5  6  7  8  9 10 11]


In [28]:
g = np.arange(1, 20, 3)
print(g)

[ 1  4  7 10 13 16 19]


In [32]:
h = np.arange(8).reshape(2, 4) #重新定义矩阵形状
print(h)

[[0 1 2 3]
 [4 5 6 7]]
