In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[1,1,2],
              [2,3,3]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 1 2]
 [2 3 3]]


In [4]:
print(a + b)

[[2 3 5]
 [6 8 9]]


In [5]:
print(a - b)

[[0 1 1]
 [2 2 3]]


In [6]:
print(a * b)

[[ 1  2  6]
 [ 8 15 18]]


In [8]:
print(a ** b) #乘幂

[[  1   2   9]
 [ 16 125 216]]


In [9]:
print(a / b)

[[1.         2.         1.5       ]
 [2.         1.66666667 2.        ]]


In [10]:
print(a % b)

[[0 0 1]
 [0 2 0]]


In [11]:
print(a // b)

[[1 2 1]
 [2 1 2]]


In [12]:
print(a + 2)

[[3 4 5]
 [6 7 8]]


In [13]:
print(a * 10)

[[10 20 30]
 [40 50 60]]


In [14]:
c = a > 3
print(c)

[[False False False]
 [ True  True  True]]


In [18]:
one = np.ones((3,5))
print(a)
print(one)

[[1 2 3]
 [4 5 6]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 矩阵运算

In [24]:
a.dot(one)
np.dot(a, one) 

array([[ 6.,  6.,  6.,  6.,  6.],
       [15., 15., 15., 15., 15.]])

In [25]:
print(a)
print(a.T)
print(np.transpose(a))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
