In [1]:
import numpy as np

In [9]:
r1 = np.random.random((3,2)) #生成3行2列从0到1的随机数
print(r1)

[[0.32596356 0.51881047]
 [0.26185179 0.50989635]
 [0.98722868 0.16611892]]


In [10]:
r2 = np.random.normal(size = (3,2)) #生成3行2列符合标准正态分布的随机数
print(r2)

[[-1.2124574  -0.71144665]
 [ 0.15485328 -0.19160559]
 [-0.64950716 -2.07646376]]


In [11]:
r3 = np.random.randint(0, 10, size=(3,2)) #生成3行2列从0到10的随机整数
print(r3)

[[2 2]
 [2 3]
 [9 1]]


In [17]:
np.sum(r1)

2.7698697746277636

In [15]:
np.min(r1)
np.max(r1)

0.9872286773990558

In [32]:
print(np.sum(r1, axis=0)) #对列求和
print(np.sum(r1, axis=1)) #对行求和

[1.57504403 1.19482575]
[0.84477404 0.77174814 1.1533476 ]


In [33]:
print(np.argmin(r1)) #最小值的索引
print(np.argmax(r1)) #最小值的索引

5
4


In [34]:
#平均值
print(np.mean(r1))
print(r1.mean())

0.4616449624379606
0.4616449624379606


In [41]:
#中位数
np.median(r1)

0.4179299552547302


In [42]:
#开方
np.sqrt(r1)

array([[0.57093219, 0.72028499],
       [0.51171456, 0.71407027],
       [0.99359382, 0.40757689]])

In [46]:
rand = np.random.randint(0,10,(1,19))
print(rand)

[[8 4 5 9 8 8 7 0 6 7 0 0 5 9 0 3 5 9 3]]


In [49]:
print(np.sort(rand)) #排序
print(np.sort(r1)) #对每行分别排序

[[0 0 0 0 3 3 4 5 5 5 6 7 7 8 8 8 9 9 9]]
[[0.32596356 0.51881047]
 [0.26185179 0.50989635]
 [0.16611892 0.98722868]]


In [51]:
np.clip(rand, 2, 8) #控制数字范围

array([[8, 4, 5, 8, 8, 8, 7, 2, 6, 7, 2, 2, 5, 8, 2, 3, 5, 8, 3]])