In [1]:
import numpy as np

In [2]:
arr1 = np.arange(2,14)
print(arr1)

[ 2  3  4  5  6  7  8  9 10 11 12 13]


In [16]:
print(arr1[3])
print(arr1[1:4])
print(arr1[2:-8])
print(arr1[:3])
print(arr1[-3:])

5
[3 4 5]
[4 5]
[2 3 4]
[11 12 13]


In [17]:
arr2 = arr1.reshape(3,4)
print(arr2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [24]:
print(arr2[1])
print(arr2[1][1])
print(arr2[1,1])
print(arr2[:2])
print(arr2[-1:])

[6 7 8 9]
7
7
[[2 3 4 5]
 [6 7 8 9]]
[[10 11 12 13]]


In [25]:
for i in arr2: #迭代行
    print(i)

[2 3 4 5]
[6 7 8 9]
[10 11 12 13]


In [30]:
for i in arr2.T: #迭代列
    print(i)

[ 2  6 10]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]


In [31]:
for i in arr2.flat: #迭代每一个元素
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13
